name: HumineChallenge
author: MizakiGaming
version: 2.1b
main: fr.humine.main.ChallengeMain
commands:
  pass:
    usage:
    description:
    permission:
  token:
    usage:
    description:
    permission:
  createpalier:
    usage:
    description:
    permission:
  palierload:
    usage:
    description:
    permission:
  palierparticlecosmetique:
    usage:
    description:
    permission:
  paliermaterialhatcosmetique:
    usage:
    description:
    permission:
  addchallengekill:
    usage:
    description:
    permission:
  addchallengeplaceblock:
    usage:
    description:
    permission:
  dailychallenge:
    usage:
    description:
    permission:
  addchallengebreakcommand:
    usage:
    description:
    permission:
  addchallengebiomediscover:
    usage:
    description:
    permission:
