name: HumineDailyChallenge
main: com.humine.main.ChallengeMain
author: MizakiGaming
version: 1.0a
commands:
  createmission:
  
  createdailychallenge:
   
  showmissions:
  
  insertmissions:
  
  showdaily:
  
  token:
   